name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Read README.md
      id: read
      uses: juliangruber/read-file-action@v1
      with:
        path: README.md
    - name: Echo README.md with cowsay
      uses: Code-Hex/neo-cowsay-action@v1
      with:
        message: ${{ steps.read.outputs.content }}