name: Bonjour
on:
  - push
jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout git
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      id: read
      with:
        go-version-file: 'go.mod'
    - name: Check Go Version
      run: go version
    - name: Build application
      run: make build